name: CI Deploy VRDISTRIBUCION

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
          
      - name: copy into folder dependencies
        run: |
            echo $PWD
            cd ${{ github.workspace }}
            ls -la

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 22.20.0
      - name: npm run build
        run: |
            echo $PWD
            ls -la
            npm -v
            npm install
            npm run build
            ls -la

      - name: Publish
        uses: dannybombastic/ssh-scp-ssh-pipelines@v1.1.5
        with:
            host: ${{ secrets.REMOTE_HOST }}
            port: 8549
            user: ${{ secrets.REMOTE_USER }}
            pass: ${{ secrets.REMOTE_PASS }}
            connect_timeout: 10s
            first_ssh: |
              rm -rf /home/dannybombastic/ruxx/ruxx/*
            scp: |
                "./dist/*" => /home/dannybombastic/ruxx/ruxx
            last_ssh: |
                cd /home/dannybombastic/ruxx
                docker compose up --build
